---
title: "Modelling Burger"
author: 'Noémie Wellinger'
date: "`r Sys.Date()`"
output: html_document
---

```{r Load packages, include=FALSE, message=FALSE, warning=FALSE}}
# Decide which packages you need. For this Project you need the following:
packages <- c("ggplot2","tidyverse","lubridate",
              "dplyr","caret","vip","parsnip",
              "workflows","tune","dials","stringr","terra","stars","sf",
              "doParallel","terrainr","starsExtra", "pdp", "kableExtra", "recipes","Boruta", "plotly")

source("../R/load_packages.R")
load_packages(packages)
```

# 1. Model identical to Burger 2022
## First, run Burger model for Bern
```{r}
Masterfile <- read.csv(
  file = "../data/Bern_Burger/MF_Zoll_mean_220131.csv",
  sep = ";",
  dec = ".",
  header = TRUE,
  fileEncoding = "latin1"  # Handles ä, ö, ü, ß etc.
)

Masterfile <- Masterfile |>
  rename(SW = S_Wind,
         NR = Nightrain_c,
         GS = Globalstrahlung)

QM_TPI_500_Model<-mutate(Masterfile, UHI_est=6.035e-01-(8.310e-03*AltDif)-(2.869e-01*GA_25)+(1.006e+00*BUL_250)-(6.103e-01*AC_750)-(2.332e-02*VH_150)-(7.164e-01*FO_1000)-
                           (3.140e-03*TPI_500)-(4.913e-01*SW)-(9.963e-01*NR)+(6.563e-03*GS)+
                           (4.705e-05*(GS*AltDif))-(1.945e-03*(GS*GA_25))+(4.572e-03*(GS*BUL_250))-(1.029e-02*(GS*AC_750))-(1.351e-04*(GS*VH_150))-(6.211e-03*(GS*FO_1000))+(6.031e-05*(GS*TPI_500))-
                           (1.396e-03*(SW*AltDif))-(4.788e-01*(SW*BUL_250))+(3.482e-01*(SW*AC_750))+(3.748e-01*(SW*FO_1000))-(8.287e-03*(SW*VH_150))-
                           (5.562e-03*(NR*AltDif))+(3.294e-01*(NR*GA_25))+(1.630e+00*(NR*AC_750))+(1.239e+00*(NR*FO_1000))+(2.038e-02*(NR*VH_150))-(5.588e-03*(NR*TPI_500)))

lm <- lm(Diff_Zoll ~ UHI_est, data=QM_TPI_500_Model)
summary(lm)
R2 <- round(summary(lm)$r.squared, 3)
RMSE<-round(summary(lm)$sigma, 3)
MBE<-round(mean(QM_TPI_500_Model$UHI_est - QM_TPI_500_Model$Diff_Zoll, na.rm = TRUE), 3)

ggplot(QM_TPI_500_Model, mapping=aes(x=UHI_est, y= Diff_Zoll)) +
  geom_point(alpha = 0.2) +
  labs(x="UHI intensity predicted [K]", 
       y="UHI intensity measured [K]", 
       title="Interaction model TPI Bern", 
              subtitle = substitute(
          R^2 == r2 ~ "; RMSE =" ~ rmse ~ "K" ~ "; MBE =" ~ mbe ~ "K",
          list(r2 = R2, rmse = RMSE, mbe = MBE)
        )
  ) +
  # geom_text(x=-1.5, y=5.5, label= paste("R2 =", R2), color="orange") +
  # geom_text(x=-1.5, y=4.5, label= paste("RMSE=", RMSE), color="orange") +
  xlim(c(-4.5,6)) +
  ylim(c(-4.5,6)) +
  geom_abline(intercept=0, slope=1, color="red") +
  theme_bw()
ggsave("../results/models/Burger_Bern/Burger_Bern_TPI_500.png", width=6.5, height=4, dpi=300)

```


## Run Burger model for Thun
```{r Load data, include=FALSE, message=FALSE, warning=FALSE}
# Load the daily data
Masterfile <- readRDS("../data/final_predictors/all_data_daily.rds")

Masterfile <- Masterfile |>
  filter(daynight == "n") |> # only night data)
  select(UHI,
         UHI_LCD,
         TA_LCD = air_temp_LCD,
         TA = air_temp,
         Log_NR,
         AltDif = AD, 
         GA_25 = OS_GA_25,
         BUL_250 = LC_B_250,
         AC_750 = OS_AC_750,
         FO_1000 = OS_FO_1000,
         TPI_500 = TPI_500,
         SW = wind_S,
         NR = precip_boolean,
         GS = rad_1d,
         VH_150 = VH_175,
         time) |>
  filter(time<="2024-09-01" & time >= "2024-06-01") |> # filter for JJA
  drop_na()


QM_TPI_500_Model<-mutate(Masterfile, UHI_est=6.035e-01-(8.310e-03*AltDif)-(2.869e-01*GA_25)+(1.006e+00*BUL_250)-(6.103e-01*AC_750)-(2.332e-02*VH_150)-(7.164e-01*FO_1000)-
                           (3.140e-03*TPI_500)-(4.913e-01*SW)-(9.963e-01*NR)+(6.563e-03*GS)+
                           (4.705e-05*(GS*AltDif))-(1.945e-03*(GS*GA_25))+(4.572e-03*(GS*BUL_250))-(1.029e-02*(GS*AC_750))-(1.351e-04*(GS*VH_150))-(6.211e-03*(GS*FO_1000))+(6.031e-05*(GS*TPI_500))-
                           (1.396e-03*(SW*AltDif))-(4.788e-01*(SW*BUL_250))+(3.482e-01*(SW*AC_750))+(3.748e-01*(SW*FO_1000))-(8.287e-03*(SW*VH_150))-
                           (5.562e-03*(NR*AltDif))+(3.294e-01*(NR*GA_25))+(1.630e+00*(NR*AC_750))+(1.239e+00*(NR*FO_1000))+(2.038e-02*(NR*VH_150))-(5.588e-03*(NR*TPI_500)))

lm <- lm(UHI~ UHI_est, data=QM_TPI_500_Model)
summary(lm)
R2 <- round(summary(lm)$r.squared, 3)
RMSE<-round(summary(lm)$sigma, 3)
MBE<-round(mean(QM_TPI_500_Model$UHI_est - QM_TPI_500_Model$UHI, na.rm = TRUE), 3)

ggplot(QM_TPI_500_Model, mapping=aes(x=UHI_est, y= UHI)) +
  geom_point(alpha = 0.2) +
    labs(x="UHI intensity predicted [K]", 
       y="UHI intensity measured [K]", 
       title="Interaction model TPI Thun (calibrated on Bern)", 
       subtitle = substitute(
          R^2 == r2 ~ "; RMSE =" ~ rmse ~ "K" ~ "; MBE =" ~ mbe ~ "K",
          list(r2 = R2, rmse = RMSE, mbe = MBE)
        )
  ) +
  xlim(c(-4.5,6)) +
  ylim(c(-4.5,6)) +
  geom_abline(intercept=0, slope=1, color="red") +
  theme_bw()
ggsave("../results/models/Burger_Thun/model_summary.png", width=6.5, height=4, dpi=300)
```

Data Splitting
```{r}
Masterfile <- readRDS("../data/final_predictors/all_data_daily.rds") 

Masterfile <- Masterfile |>
  filter(daynight == "n") |> # only night data)
  # drop rows where air_temp_LCD, UHI or UHI_LCD is NA
  filter(!is.na(air_temp_LCD) | !is.na(UHI) | !is.na(UHI_LCD)) |>
  mutate(CAP9 = as.factor(CAP9),
         CAP18 = as.factor(CAP18),
         CAP27 = as.factor(CAP27),
         GWT8_Z500 = as.factor(GWT8_Z500),
         GWT10_SLP = as.factor(GWT10_SLP),
         GWT10_Z500 = as.factor(GWT10_Z500),
         GWT18_SLP = as.factor(GWT18_SLP),
         GWT18_Z500 = as.factor(GWT18_Z500),
         GWT26_SLP = as.factor(GWT26_SLP),
         GWT26_Z500 = as.factor(GWT26_Z500)
  )

set.seed(123)  # for reproducibility
split <- rsample::initial_split(Masterfile, prop = 0.8, strata = "UHI")
Masterfile_train <- rsample::training(split)
Masterfile_test <- rsample::testing(split)

# Choose for which variables you want a density plot
vars_to_plot <- c("UHI", "air_temp", "rad", "wind_vel", "precip", "precip_boolean", "water_temp", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500")

plot_data <- Masterfile_train |> 
  mutate(split = "train") |> 
  bind_rows(Masterfile_test |> mutate(split = "test")) |> 
  pivot_longer(cols = all_of(vars_to_plot), names_to = "variable", values_to = "value")

plot_data |> 
  ggplot(aes(x = value, y = ..density.., color = split)) +
  geom_density() +
  facet_wrap(~variable, scales = "free")
```

```{r}
# Load helper functions
source("../R/LUR_int_model.R")
source("../R/map_helpers.R")

# load daily measurement data
  measurement_data <- read.csv("../data/Thun Messnetz 2024/Thun_daily_summary_2024-05-01_2024-10-30.csv") |>
    mutate(time = as.POSIXct(time, format = "%Y-%m-%dT%H:%M:%OS", tz="UTC")) |>
    mutate(time = with_tz(time, tzone = "Europe/Zurich")) #should start at 2024-05-01 02:00
  
# Dates to predict the models
dates = c("2024-08-23","2024-08-11", "2024-08-13", "2024-09-26") #highest UHI, average UHI, lowest UHI 
```

```{r}
# Map the UHI for a given date
Masterfile |> 
  filter(time == "2024-08-11") |> 
  ggplot(aes(x = OST_CHTOPO, y = NORD_CHTOPO, fill = UHI)) +
  geom_point(shape = 21, size = 4, color = "black") +
  scale_fill_viridis_c() +
  labs(fill = "UHI [K]", title = "UHI intensity on 2024-08-23", x = "Longitude", y = "Latitude") +
  theme_minimal()
```


```{r}
# Check the mean UHI per day
daily_means <- measurement_data |>
  group_by(time) |>
  summarise(mean_UHI_night = mean(UHI_night, na.rm = FALSE)) 
  ggplot(data = daily_means, aes(x = time, y = mean_UHI_night)) +
  geom_line() +
  labs(x = "Date", y = "Mean UHI [K]", title = "Mean nighttime UHI per day") +
  theme_minimal()
```

```{r}
meteo_predictors_daily <- readRDS("../data/final_predictors/Meteo_predictors_daily.rds")
```



# 2. Calibrate the model on Thun
```{r}
source("../R/LUR_int_model.R")
result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_S", "precip_boolean", "rad_1d"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI -> UHI night (Ref = MeteoCH)",
  model_type_short = "lur_int_tpi_UHI_night",
  plot_lim = c(-4.5,6)
)
model_type_short = "lur_int_tpi_UHI_night"
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night/"
  )
}
```


# 3. Predict absolute temperature and add temperature as a predictor
```{r}
result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "air_temp_LCD",
  target_name = "Mean night temperature",
  met_vars = c("wind_S", "precip_boolean", "rad_1d"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI -> TA night",
  model_type_short = "lur_int_tpi_ta_night",
  save_model = FALSE,
  plot_lim = c(3, 25)
)

predict_temperature_map(
  model = result$model,
  date = "2024-08-23",
  daynight = "n",
  meteo_dir = "../data/Geodata/Meteo_daily",
  lulc_dir = "../data/Geodata/LULCTopo_Thun",
  output_path = "../results/models/lur_int_tpi_ta_night/"
)


result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "air_temp_LCD",
  target_name = "Mean night temperature",
  met_vars = c("wind_S", "precip_boolean", "rad_1d", "air_temp"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI -> TA night",
  model_type_short = "lur_int_tpi_ta_night_ta",
  save_model = FALSE,
  plot_lim = c(3, 25)
)
predict_temperature_map(
  model = result$model,
  date = "2024-08-23",
  daynight = "n",
  meteo_dir = "../data/Geodata/Meteo_daily",
  lulc_dir = "../data/Geodata/LULCTopo_Thun",
  output_path = "../results/models/lur_int_tpi_ta_night_ta/"
)

```

Add more meteorological predictors
```{r}
source("../R/LUR_int_model.R")

result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_S", "precip_boolean", "rad_1d", "air_temp"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI with TA -> UHI night",
  model_type_short = "lur_int_tpi_UHI_night_ta",
  plot_lim = c(-4.5,6)
)
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night_ta/"
  )
}


result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_S", "precip_boolean", "rad_1d", "GWT18_SLP"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI with GWT18_SLP -> UHI night",
  model_type_short = "lur_int_tpi_UHI_night_GWT_18_SLP",
  plot_lim = c(-4.5,6)
)
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night_GWT_18_SLP/"
  )
}


result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_S", "precip_boolean", "rad_1d", "CAP27"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI with CAP27 -> UHI night",
  model_type_short = "lur_int_tpi_UHI_night_CAP27",
  plot_lim = c(-4.5,6)
)
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night_CAP27/"
  )
}


result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_S", "precip_boolean", "rad_1d", "water_temp_1d"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI with water_temp_1d -> UHI night",
  model_type_short = "lur_int_tpi_UHI_night_water_temp",
  plot_lim = c(-4.5,6)
)
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night_water_temp/"
  )
}


result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_S", "precip_boolean", "rad_1d", "water_temp_surface_1d"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI with water_temp_surface_1d -> UHI night",
  model_type_short = "lur_int_tpi_UHI_night_water_temp_surface",
  plot_lim = c(-4.5,6)
)
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night_water_temp_surface/"
  )
}
```


# Model with 3 additional predictors
```{r}
source("../R/LUR_int_model.R")
source("../R/map_helpers.R")

result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_S", "precip_boolean", "rad_1d", "water_temp_1d", "GWT18_SLP", "air_temp"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI with WT, GWT18, TA -> UHI night",
  model_type_short = "lur_int_tpi_UHI_night_water_ta_gwt",
  plot_lim = c(-4.5,6)
)
model_type_short = "lur_int_tpi_UHI_night_water_ta_gwt"
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night_water_ta_gwt/"
  )
}
```
# Model with 5 additional predictors
```{r}
source("../R/LUR_int_model.R")
source("../R/map_helpers.R")

result <- LUR_int_model(
  train_data = Masterfile_train,
  test_data = Masterfile_test,
  target = "UHI",
  target_name = "mean nighttime UHI",
  met_vars = c("wind_vel", "precip_boolean", "rad_1d", "water_temp_1d", "CAP27", "air_temp", "humidity_1d"),
  spat_vars = c("AD", "OS_GA_25", "LC_B_250", "OS_AC_750", "OS_FO_1000", "TPI_500", "VH_175"),
  model_type = "LUR INT TPI with TA, TW, CAP27, RH -> UHI night",
  model_type_short = "lur_int_tpi_UHI_night_additional",
  plot_lim = c(-4.5,6)
)
model_type_short = "lur_int_tpi_UHI_night_additional"
for (date in dates) {
  predict_temperature_map(
    model = result$model,
    date = date,
    daynight = "n",
    meteo_dir = "../data/Geodata/Meteo_daily",
    lulc_dir = "../data/Geodata/LULCTopo_Thun",
    output_path = "../results/models/lur_int_tpi_UHI_night_additional/"
  )
}

# plot variable importance:
library(broom)
library(ggplot2)
library(dplyr)

# Tidy the model output
coef_df <- broom::tidy(result$model) |> 
  filter(term != "(Intercept)") |>  # Remove intercept to focus on predictors
  mutate(significant = p.value < 0.05)

# Plot
ggplot(coef_df, aes(x = estimate, y = reorder(term, estimate), color = significant)) +
  geom_point() +
  geom_errorbarh(aes(xmin = estimate - 1.96*std.error, xmax = estimate + 1.96*std.error), height = 0.2) +
  scale_color_manual(values = c("TRUE" = "firebrick", "FALSE" = "gray40")) +
  labs(
    x = "Coefficient Estimate (± 95% CI)",
    y = "Predictor",
    title = "Linear Model Coefficients",
    subtitle = "Significant predictors (p < 0.05) shown in red"
  ) +
  theme_minimal()
```

```{r}
# plot predicted UHI and wind speed
data_result <- result$test_data
ggplot(data_result, aes(x = wind_vel, y = pred, color = wind_dir_class)) +
  geom_point(alpha = 0.2) +
  labs(x = "Wind speed [km/h]", y = "UHI intensity predicted [K]", title = "Predicted UHI intensity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# plot predicted UHI and wind speed
ggplot(data_result, aes(x = Log_NR, y = pred)) +
  geom_point(alpha = 0.2) +
  labs(x = "Logger", y = "UHI intensity predicted [K]", title = "Predicted UHI intensity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

# plot predicted UHI and wind speed
ggplot(data_result, aes(x = time, y = pred, color = Log_NR)) +
  geom_point(alpha = 0.2) +
  labs(x = "Logger", y = "UHI intensity predicted [K]", title = "Predicted UHI intensity") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

plotly::ggplotly(
  ggplot(data_result, aes(x = time, y = residuals, color = Log_NR)) +
  geom_point(alpha = 0.2) +
  labs(x = "Logger", y = "Residuals [K]", title = "Residuals per Logger") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
)
  #turn into plotly

ggplot(data_result, aes(x = factor(Log_NR), y = residuals, color = LU_7)) +
  geom_boxplot() +
  labs(x = "Logger", y = "Residuals [K]", title = "Residuals per logger", subtitle = model_type_short, legend = "land use type") +
  scale_color_manual(values = c("black", "darkgreen", "brown", "#44dd55", "orange", "#2255cc")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.4))
ggsave(paste0("../results/models/", model_type_short, "/residuals_Log_boxplot.png"), width=7.5, height=4, dpi=300)

ggplot(data_result, aes(x = factor(Log_NR), y = rel_error, color = LU_7)) +
  geom_boxplot(outliers = F) +
  labs(x = "Logger", y = "Relative error", title = "Relative error per logger", subtitle = model_type_short, legend = "land use type") +
  scale_color_manual(values = c("black", "darkgreen", "brown", "#44dd55", "orange", "#2255cc")) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.4))
ggsave(paste0("../results/models/", model_type_short, "/rel_err_Log_boxplot.png"), width=7.5, height=4, dpi=300)

ggplot(data_result, aes(x = pred, y = residuals, color=LU_7)) +
  geom_point(alpha = 0.7) +
  geom_hline(yintercept = 0, linetype = "dashed", width = 0.05) +
  geom_vline(xintercept = 0, linetype = "dashed", width = 0.05) +
  facet_wrap(~ Log_NR) +
  labs(x = "Predicted UHI [K]", y = "Residual [K]", title = "Residuals vs Predicted UHI per logger", subtitle = model_type_short, legend = "land use type") +
  scale_color_manual(values = c("black", "darkgreen", "brown", "#44dd55", "orange", "#2255cc")) +
  theme_minimal()
ggsave(paste0("../results/models/", model_type_short, "/residuals_Log_.png"), width=10, height=9.2, dpi=600)


ggplot(data_result, aes(x = reorder(Log_NR, RMSE_Log), y = RMSE_Log)) +
  geom_col(fill = "coral") +
  coord_flip() +
  labs(x = "Sensor", y = "RMSE", title = "RMSE per sensor") +
  theme_minimal()
ggsave(paste0("../results/models/", model_type_short, "/RMSE_Log.png"), width=7.5, height=4, dpi=300)
```

```{r}
# plot e timeseries of a logger
for (i in unique(data_result$Log_NR)) {
  loc <- data_result |> filter(Log_NR == i) |> select(Location) |> unique()
  rsq <- data_result |> filter(Log_NR == i) |> select(R2_Log) |> unique() |> round(3)
  rmse_log <- data_result |> filter(Log_NR == i) |> select(RMSE_Log) |> unique() |> round(3)
  p <- ggplot(data_result |> filter(Log_NR == i), aes(x = time)) +
    geom_line(aes(y = UHI, color = "black")) +
    geom_line(aes(y = pred, color = "red")) +
    # add rmse_log and r
    labs(x = "Date", y = "UHI [K]", 
         title = paste("UHI intensity for", i, loc), 
         color = "data",
         # subtitle = substitute(R^2 == r2 ~ "; RMSE =" ~ rmse ~ "K", list(r2 = rsq, rmse = rmse_log))) +
         subtitle = paste0("R^2 = ", rsq, "; RMSE = ", rmse_log, " K; model: ", model_type_short)) +
    # add legend
    scale_color_manual(values = c("black", "red"), labels = c("Measured", "Predicted")) +
    theme_minimal() +
    ylim(c(-1.5,5))
  print(p)
  ggsave(paste0("../results/models/",model_type_short, "/pred_vs_ms_", i, "_", model_type_short, ".png"), width=7.5, height=4, dpi=200)
}
```


Maps
```{r}
# Assuming you have coordinates like Longitude, Latitude or X, Y
ggplot(data_result, aes(x = OST_CHTOPO, y = NORD_CHTOPO, fill = RMSE_Log)) +
  scale_fill_viridis_c() +
  geom_point(shape = 21, size = 4, color = "black") +
  labs(fill = "RMSE [K]", title = "Spatial distribution of RMSE", subtitle = model_type_short,
       x = "Longitude", y = "Latitude") +
  theme_minimal()

ggplot(data_result, aes(x = OST_CHTOPO, y = NORD_CHTOPO, fill = NRMSE_Log)) +
  scale_fill_viridis_c() +
  geom_point(shape = 21, size = 4, color = "black") +
  labs(fill = "NRMSE", title = "Spatial distribution of NRMSE", subtitle = model_type_short,
       x = "Longitude", y = "Latitude") +
  theme_minimal()

ggplot(data_result, aes(x = OST_CHTOPO, y = NORD_CHTOPO, fill = R2_Log)) +
  scale_fill_viridis_c() +
  geom_point(shape = 21, size = 4, color = "black") +
  labs(fill = "R-squared", title = "Spatial distribution of R-squred", subtitle = model_type_short,
       x = "Longitude", y = "Latitude") +
  theme_minimal()

library(leaflet)
library(RColorBrewer)

library(leaflet)

# Create color palettes
pal_rmse <- colorNumeric("viridis", domain = data_result$RMSE_Log)
pal_r2   <- colorNumeric("viridis", domain = data_result$R2_Log)
pal_nrmse <- colorNumeric("viridis", domain = data_result$NRMSE_Log)

leaflet(data_result) %>%
  addProviderTiles("Stadia.StamenTerrain") %>%

  # RMSE Layer
  addCircleMarkers(
    lng = ~OST_CHTOPO, lat = ~NORD_CHTOPO,
    radius = 6,
    #fillColor = ~pal_rmse(RMSE_Log),
    fillColor = colorNumeric(palette = "viridis", domain = data_result$RMSE_Log),
    fillOpacity = 1, color = "black", weight = 1,
    group = "RMSE"
  ) %>%
  
  # R2 Layer
  addCircleMarkers(
    lng = ~OST_CHTOPO, lat = ~NORD_CHTOPO,
    radius = 6,
    fillColor = colorNumeric("viridis", domain = data_result$R2_Log),
    fillOpacity = 1, color = "black", weight = 1,
    group = "R²"
  ) %>%

  # NRMSE Layer
  addCircleMarkers(
    lng = ~OST_CHTOPO, lat = ~NORD_CHTOPO,
    radius = 6,
    fillColor = colorNumeric("viridis", domain = data_result$NRMSE_Log),
    fillOpacity = 1, color = "black", weight = 1,
    group = "NRMSE"
  ) %>%

  # Layer Control
  addLayersControl(
    baseGroups = c("RMSE", "R²", "NRMSE"),
    options = layersControlOptions(collapsed = FALSE)
  ) %>%

  # Add Legends (all at once; alternatively, use only one at a time if using `leaflet.extras2`)
  addLegend("bottomright", pal = pal_rmse, values = ~RMSE_Log, title = "RMSE [K]", group = "RMSE") %>%
  addLegend("bottomright", pal = pal_r2, values = ~R2_Log, title = "R²", group = "R²") %>%
  addLegend("bottomright", pal = pal_nrmse, values = ~NRMSE, title = "NRMSE", group = "NRMSE")



```



```{r predictors}
# Define the predictors

# Take all column-names you need as predictors from the combined file except the defined
predictors <- combined |>
  dplyr::select(-c(Log_Nr,temperature,timestamp,Name,NORD_CHTOP,OST_CHTOPO,year,month,day,hour,LV_03_E,LV_03_N)) |>
  colnames()


```


