---
title: "Tagesverlauf"
author: 'Noémie Wellinger'
date: "`r Sys.Date()`"
output: html_document
---


```{r libs, include = F}
library(dplyr)
library(tidyverse)
library(lubridate)
library(ggplot2)
library(readr)
```

#-------------------------------------------------------------------------------
# Bern
```{r get_data, include = F}
# Get data from current year for stations Bundesplatz and Zollikofen 3m
new_BuPla_Zoll <- read_csv("../data/Analysis 2023/Rawdata_T_2023_JJA.csv")
new_BuPla_Zoll <- new_BuPla_Zoll |> 
  dplyr::select(Time, Log_70, Log_99) |>
  mutate(Time = as.POSIXct(Time, format = "%Y-%m-%d %H:%M", tz = "Europe/Zurich")) |>
  mutate(month = month(Time), day = day(Time), hour = hour(Time), minute = minute(Time)) 

# Get diurnal cycles from previous years
BuPla_Zoll <- read.csv("../data/Analysis 2022/UHI_BuPla_Zoll.csv", sep = ",", dec = ".") |>
  mutate(Time = as.POSIXct(Time, format = "%Y-%m-%dT%H:%M:%OS", tz = "GMT")) |>
  mutate(Time = as.POSIXct(Time, tz = "Europe/Zurich")) |>
  mutate(month = month(Time), day = day(Time), hour = hour(Time), minute = minute(Time))

# Join the two together
new_BuPla_Zoll <- new_BuPla_Zoll |>
  dplyr::full_join(BuPla_Zoll, by = c("month", "day", "hour", "minute")) |>
  rename(Time = Time.x,
         Log_70_23 = Log_70,
         Log_99_23 = Log_99) |>
  dplyr::select(-month, -day, -hour, -minute, -Time.y)

# Calculate UHI for current year
new_BuPla_Zoll <- new_BuPla_Zoll |>
  mutate(UHI_23 = Log_70_23 - Log_99_23)

#save CSV for nex year's analysis
write_csv(new_BuPla_Zoll, ("../data/Analysis 2023/UHI_BuPla_Zoll.csv"))
```

```{r}
BuPla_Zoll <- read.csv("../data/Analysis 2022/UHI_BuPla_Zoll.csv", sep = ",", dec = ".") |>
  mutate(Time = as.POSIXct(Time, format = "%Y-%m-%dT%H:%M:%OS", tz = "GMT")) |>
  mutate(Time = as.POSIXct(Time, tz = "Europe/Zurich")) 

write_csv(BuPla_Zoll, ("../data/Analysis 2022/UHI_BuPla_Zoll.csv"))


BuPla_Zoll <- read.csv("../data//Analysis 2022/BuPla_Zoll_22.csv", sep = ";", dec = ".") |>
  mutate(Time = as.POSIXct(Zeit, format = "%d.%m.%Y %H:%M", tz = "Europe/Zurich")) |>
  mutate(UHI_22 = Log_70_22 - Log_99_22,
         UHI_21 = Log_70_21 - Log_99_21,
         UHI_20 = Log_70_20 - Log_99_20,
         UHI_19 = Log_70_19 - Log_99_19,
         UHI_18 = Log_70_18 - Log_99_18) |>
  dplyr::select(-Zeit)
  
```


```{r diurnal, include = F}
# Calculate diurnal cycles
BuPla_Zoll_diurnal <- new_BuPla_Zoll |>
  drop_na(Time) |>
  #filter(month(Time) == 7) |>
  dplyr::select(Time, UHI_23, UHI_22, UHI_21, UHI_20, UHI_19, UHI_18) |>
  dplyr::group_by(hour = hour(Time)) |>
  dplyr::summarize(UHI_23 = mean(UHI_23, na.rm=T),
                   UHI_22 = mean(UHI_22, na.rm=T),
                   UHI_21 = mean(UHI_21, na.rm=T),
                   UHI_20 = mean(UHI_20, na.rm=T),
                   UHI_19 = mean(UHI_19, na.rm=T),
                   UHI_18 = mean(UHI_18, na.rm=T)
                   )

# rearrange the time, so that the timeseries starts at 12am (noon) and midnight is in the middle
am <- BuPla_Zoll_diurnal |>
  dplyr::filter(hour <= 11) |>
  mutate(hour_shift = hour + 12)

# Combine tables
BuPla_Zoll_diurnal <- BuPla_Zoll_diurnal |>
  dplyr::filter(hour >= 12) |>
  mutate(hour_shift = hour - 12) |>
  add_row(am)
```


```{r plot}
Bupla <-
  ggplot(BuPla_Zoll_diurnal, mapping=aes(x=hour_shift)) +
  geom_line(aes(y = UHI_18,color="2018"), lwd=1.2) +
  geom_line(aes(y = UHI_19,color="2019"), lwd=1.2) +
  geom_line(aes(y = UHI_20,color="2020"), lwd=1.2) +
  geom_line(aes(y = UHI_21,color="2021"), lwd=1.2) +
  geom_line(aes(y = UHI_22,color="2022"), lwd=1.5) +
  geom_line(aes(y = UHI_23,color="2023"), lwd=1.5) +
  geom_hline(yintercept = 0, lty=3) +
  geom_hline(yintercept = 1, lty=3) +
  geom_hline(yintercept = 2, lty=3) +
  geom_hline(yintercept = 3, lty=3) +
  theme_bw() +
  scale_x_continuous(breaks = unique(BuPla_Zoll_diurnal$hour_shift), labels = BuPla_Zoll_diurnal$hour, minor_breaks=NULL) +
  # scale_x_discrete(limits=c("12","13","14","15","16","17","18","19","20","21","22","23","0","1","2","3","4","5","6",
  #                          "7","8","9","10","11"))+
  scale_y_continuous(breaks=seq(0,3,0.5), minor_breaks=NULL) +
  labs(y = "°C",
       x = "Tageszeit MESZ",
       title = "Städtischer Wärmeinsel-Effekt",
       subtitle = "Temperaturdifferenz Bundesplatz - Zollikofen")+
  scale_colour_manual(values=c("grey", "blue", "gold", "red", "forestgreen", "black"), breaks=c("2018", "2019", "2020", "2021", "2022", "2023"), name="") +
  theme(legend.position=c(0.50,0.07), legend.direction = "horizontal", legend.background=element_rect(fill="white", color="black"))


Bupla
```

```{r export, include=F}
ggsave("UHI_BuPla_23.jpg", Bupla, path="../Figures/2023", width=8, height=7)
```

#-------------------------------------------------------------------------------
# Ostermundigen

```{r}
# Get data from current year for stations in Ostermundigen and Zollikofen 3m
new_OM_Zoll <- read_csv("../data/Analysis 2023/Rawdata_T_2023_JJA.csv")|> 
  dplyr::select(Time, Log_99, Log_151, Log_86, Log_154) |>
  mutate(Time = as.POSIXct(Time, format = "%Y-%m-%d %H:%M", tz = "Europe/Zurich")) |>
  mutate(month = month(Time), day = day(Time), hour = hour(Time), minute = minute(Time)) 

# Data from previous year
old_OM_Zoll <- read.csv("../data/Analysis 2022/Rawdata_2022_JJA_OM.csv", sep = ";", dec = ".") |>
  dplyr::select(Zeit, Log_99, Log_151, Log_86, Log_154) |>
  mutate(Time = as.POSIXct(Zeit, format = "%d.%m.%Y %H:%M", tz = "Europe/Zurich")) |>
  mutate(month = month(Time), day = day(Time), hour = hour(Time), minute = minute(Time)) |>
  rename(Log_99_22 = Log_99, Log_151_22 = Log_151, Log_86_22 = Log_86, Log_154_22 = Log_154) |>
  mutate(UHI_151_22 = Log_151_22 - Log_99_22,
         UHI_86_22 = Log_86_22 - Log_99_22,
         UHI_154_22 = Log_154_22 - Log_99_22) |>
  dplyr::select(-Zeit)

write_csv(old_OM_Zoll, ("../data/Analysis 2022/OM_Zoll_22.csv"))

# Join the two together
new_OM_Zoll <- new_OM_Zoll |>
  dplyr::full_join(old_OM_Zoll, by = c("month", "day", "hour", "minute")) |>
  rename(Time = Time.x,
         Log_99_23 = Log_99,
         Log_151_23 = Log_151,
         Log_86_23 = Log_86,
         Log_154_23 = Log_154) |>
  dplyr::select(-month, -day, -hour, -minute, -Time.y)

# Calculate UHI for current year
new_OM_Zoll <- new_OM_Zoll |>
  mutate(UHI_151_23 = Log_151_23 - Log_99_23,
         UHI_86_23 = Log_86_23 - Log_99_23,
         UHI_154_23 = Log_154_23 - Log_99_23)

#save CSV for nex year's analysis
write_csv(new_OM_Zoll, ("../data/Analysis 2023/UHI_OM_Zoll.csv"))
```

```{r diurnal, include = F}
# Calculate diurnal cycles
OM_Zoll_diurnal <- new_OM_Zoll |>
  drop_na(Time) |>
  #filter(month(Time) == 7) |>
  dplyr::select(Time, UHI_151_23, UHI_151_22, UHI_86_23, UHI_86_22, UHI_154_23, UHI_154_22) |>
  dplyr::group_by(hour = hour(Time)) |>
  dplyr::summarize(UHI_151_23 = mean(UHI_151_23, na.rm=T),
                   UHI_151_22 = mean(UHI_151_22, na.rm=T),
                   UHI_86_23 = mean(UHI_86_23, na.rm=T),
                   UHI_86_22 = mean(UHI_86_22, na.rm=T),
                   UHI_154_23 = mean(UHI_154_23, na.rm=T),
                   UHI_154_22 = mean(UHI_154_22, na.rm=T)
                   )

# rearrange the time, so that the timeseries starts at 12am (noon) and midnight is in the middle
am <- OM_Zoll_diurnal |>
  dplyr::filter(hour <= 11) |>
  mutate(hour_shift = hour + 12)

# Combine tables
OM_Zoll_diurnal <- OM_Zoll_diurnal |>
  dplyr::filter(hour >= 12) |>
  mutate(hour_shift = hour - 12) |>
  add_row(am)
```

```{r plot}
plot <-
  ggplot(OM_Zoll_diurnal, mapping=aes(x=hour_shift)) +
  geom_line(aes(y = UHI_151_23,color="BäreTower 2023"), ylim = c(-1, 2.5), lwd=1.5) +
  geom_line(aes(y = UHI_151_22,color="BäreTower 2022"), lwd=1.5) +
  geom_line(aes(y = UHI_86_23,color="Lötschenstr. 2023"), lwd=1.5) +
  geom_line(aes(y = UHI_86_22,color="Lötschenstr. 2022"), lwd=1.5) +
  geom_line(aes(y = UHI_154_23,color="Oberfeld 2023"), lwd=1.5) +
  geom_line(aes(y = UHI_154_22,color="Oberfeld 2022"), lwd=1.5) +
  #geom_hline(yintercept = -1, lty=0) +
  geom_hline(yintercept = 0, lty=3) +
  geom_hline(yintercept = 1, lty=3) +
  geom_hline(yintercept = 2, lty=3) +
  theme_bw() +
  scale_x_continuous(breaks = unique(OM_Zoll_diurnal$hour_shift), labels = OM_Zoll_diurnal$hour, minor_breaks=NULL) +
  scale_y_continuous(breaks=seq(0,2.5,0.5), minor_breaks=NULL) +
  labs(y = "°C",
       x = "Tageszeit MESZ",
       title = "Städtischer Wärmeinsel-Effekt",
       subtitle = "Temperaturdifferenzen zur Messstation Bern/Zollikofen")+
  scale_colour_manual(values=c("darkred", "coral2", "#6030b0", "#bb55ee", "#116633", "#66cc66"), breaks=c("BäreTower 2023", "BäreTower 2022", "Lötschenstr. 2023", "Lötschenstr. 2022", "Oberfeld 2023", "Oberfeld 2022"), name="") +
  theme(legend.position="bottom", legend.direction = "horizontal", legend.background=element_rect(fill="white", color="black"))


plot
```

```{r export, include=F}
ggsave("UHI_OM_23.jpg", plot, path="../Figures/2023", width=8, height=7)
```
