---
title: "Variable Selection"
author: 'Noémie Wellinger'
date: "`r Sys.Date()`"
output: html_document
---

```{r}
source("../R/load_packages.R")
load_packages(c("dplyr", "ggplot2", "lubridate", "ggpubr", "lsr", "ggfortify"))
```

Correlation between UHI and predictors
```{r setup, include=FALSE}
meteo_all <- readRDS("../data/final_predictors/all_data_daily.rds")

meteo_all_aggr <- meteo_all |>
  filter(daynight == "n") |>
  group_by(time) |>
  summarise(
    UHI = mean(UHI, na.rm = TRUE),
    wind_vel = first(wind_vel),
    wind_vel_1d = first(wind_vel_1d),
    wind_dir = first(wind_dir),
    wind_dir_1d = first(wind_dir_1d),
    wind_dir_class = first(wind_dir_class),
    wind_dir_1d_class = first(wind_dir_1d_class),
    wind_dir_NS = first(wind_dir_NS),
    wind_dir_1d_NS = first(wind_dir_1d_NS),
    wind_S = first(wind_S),
    wind_S_1d = first(wind_S_1d),
    rad = first(rad),
    rad_1d = first(rad_1d),
    humidity = first(humidity),
    humidity_1d = first(humidity_1d),
    pressure = first(pressure),
    pressure_1d = first(pressure_1d),
    air_temp = first(air_temp),
    air_temp_1d = first(air_temp_1d),
    water_temp = first(air_temp),
    water_temp_1d = first(water_temp_1d),
    precip = first(precip),
    precip_1d = first(precip_1d),
    precip_boolean = first(precip_boolean),
    precip_1d_boolean = first(precip_1d_boolean),
    CAP9 = as.factor(first(CAP9)),
    CAP18 = as.factor(first(CAP18)),
    CAP27 = as.factor(first(CAP27)),
    GWT8_Z500 = as.factor(first(GWT8_Z500)),
    GWT10_SLP = as.factor(first(GWT10_SLP)),
    GWT10_Z500 = as.factor(first(GWT10_Z500)),
    GWT18_SLP = as.factor(first(GWT18_SLP)),
    GWT18_Z500 = as.factor(first(GWT18_Z500)),
    GWT26_SLP = as.factor(first(GWT26_SLP)),
    GWT26_Z500 = as.factor(first(GWT26_Z500))
  ) |>
  ungroup()

```

```{r}
# Filter and compute r for each wind direction
cor_df <- meteo_all_aggr |>
  filter(wind_vel < 10) |>
  group_by(wind_dir_NS) |>
  summarise(r = cor(wind_vel, UHI, use = "complete.obs")) |>
  mutate(r_label = paste0("r (", wind_dir_NS, ") = ", round(r, 2))) |>
  pull(r_label)

# Combine into one subtitle string
subtitle_text <- paste(cor_df, collapse = "; ")

# Plot with subtitle
meteo_all_aggr |>
  ggplot(aes(x = wind_vel, y = UHI, color = wind_dir_NS)) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = "Correlation: nighttime UHI and Wind Speed",
    subtitle = subtitle_text,
    x = "Wind Speed (km/h)",
    y = "UHI [K]",
    color = "Wind Direction"
  ) +
  theme_classic() +
  scale_color_manual(values = c("N" = "darkorange", "S" = "darkcyan")) +
  theme(legend.position = "inside", legend.box = "vertical", 
        legend.justification = c(1,1),
        legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8))

ggsave("../results/Variable Selection/WindSpeed_vs_UHI_wind_dir.png", width = 5, height = 5.5, dpi = 300)

```


```{r}
# list with all the variables and their names for the plot titles
variables_num <- list(
  list(name = "wind_vel", title = "Wind Speed [km/h]", descr = "Wind Speed (8h)"),
  list(name = "wind_vel_1d", title = "Wind Speed 1d [km/h]", descr = "Wind Speed (24h)"),
  list(name = "wind_S", title = "Southern Wind Component", descr = "South Wind (8h)"),
  list(name = "wind_S_1d", title = "Southern Wind Component 1d", descr = "South Wind (24h)"),
  list(name = "rad", title = "Global Solar Radiation [W/m²]", descr = "Global Radiation (8h)"),
  list(name = "rad_1d", title = "Global Solar Radiation 1d [W/m²]", descr = "Global Radiation (24h)"),
  list(name = "humidity", title = "Relative Humidity [%]", descr = "Relative Humidity (8h)"),
  list(name = "humidity_1d", title = "Relative Humidity 1d [%]", descr = "Relative Humidity (24h)"),
  list(name = "pressure", title = "Air Pressure [hPa]", descr = "Air Pressure (8h)"),
  list(name = "pressure_1d", title = "Air Pressure 1d [hPa]", descr = "Air Pressure (24h)"),
  list(name = "air_temp", title = "Air Temperature [°C]", descr = "Air Temperature (8h)"),
  list(name = "air_temp_1d", title = "Air Temperature 1d [°C]", descr = "Air Temperature (24h)"),
  list(name = "water_temp", title = "Water Temperature [°C]", descr = "Water Temperature (8h)"),
  list(name = "water_temp_1d", title = "Water Temperature 1d [°C]", descr = "Water Temperature (24h)"),
  list(name = "precip", title = "Precipitation [mm]", descr = "Precipitation (8h)"),
  list(name = "precip_1d", title = "Precipitation 1d [mm]", descr = "Precipitation (24h)")
  # list(name = "precip_boolean", title = "Precipitation Occurrence", descr = "Whether precipitation occurred"),
  # list(name = "precip_1d_boolean", title = "Precipitation Occurrence 1d", descr = "Daily precipitation occurrence")
)

variables_fact <- list(
  list(name = "wind_dir", title = "Wind Direction [°]", descr = "Instantaneous wind direction"),
  list(name = "wind_dir_1d", title = "Wind Direction 1d [°]", descr = "Daily average wind direction"),
  list(name = "wind_dir_class", title = "Wind Direction Class", descr = "Wind direction class (categorical)"),
  list(name = "wind_dir_1d_class", title = "Wind Direction 1d Class", descr = "Daily wind direction class"),
  list(name = "wind_dir_NS", title = "North-South Wind Component", descr = "Instantaneous N–S wind component"),
  list(name = "wind_dir_1d_NS", title = "North-South Wind Component 1d", descr = "Daily N–S wind component"),
  list(name = "CAP9", title = "Circulation Type CAP9", descr = "Circulation type class (9 types)"),
  list(name = "CAP18", title = "Circulation Type CAP18", descr = "Circulation type class (18 types)"),
  list(name = "CAP27", title = "Circulation Type CAP27", descr = "Circulation type class (27 types)"),
  list(name = "GWT8_Z500", title = "GWT8 Z500", descr = "Großwettertyp (8 types) from Z500 field"),
  list(name = "GWT10_SLP", title = "GWT10 SLP", descr = "Großwettertyp (10 types) from SLP field"),
  list(name = "GWT10_Z500", title = "GWT10 Z500", descr = "Großwettertyp (10 types) from Z500 field"),
  list(name = "GWT18_SLP", title = "GWT18 SLP", descr = "Großwettertyp (18 types) from SLP field"),
  list(name = "GWT18_Z500", title = "GWT18 Z500", descr = "Großwettertyp (18 types) from Z500 field"),
  list(name = "GWT26_SLP", title = "GWT26 SLP", descr = "Großwettertyp (26 types) from SLP field"),
  list(name = "GWT26_Z500", title = "GWT26 Z500", descr = "Großwettertyp (26 types) from Z500 field")
)


# Loop through each variable and create a scatter plot

for (var in variables_num) {
  var_name <- var$name
  var_title <- var$title
  var_descr <- var$descr

  # Calculate Pearson correlation coefficient
  r_val <- cor(meteo_all_aggr[[var_name]], meteo_all_aggr$UHI, use = "complete.obs")
  r_text <- paste0("r = ", round(r_val, 2))

  p <- ggplot(meteo_all_aggr, aes(x = !!sym(var_name), y = UHI)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(
      title = paste("Correlation: nighttime UHI and", var_descr),
      subtitle = r_text,
      x = var_title,
      y = "UHI [K]"
    ) +
    theme_classic() +
    theme(legend.position = "none")
  
  print(p)
  ggsave(paste0("../results/Variable Selection/", var_name, "_vs_UHI.png"), plot = p, 
         width = 5, height = 5.5, dpi = 300)
}
```

Correlation tests for categorical variables like weather type
```{r}
variables_fact <- list(
  list(name = "wind_dir_class", title = "Wind Direction Class", descr = "Wind direction class (categorical)"),
  list(name = "wind_dir_1d_class", title = "Wind Direction 1d Class", descr = "Daily wind direction class"),
  list(name = "wind_dir_NS", title = "North-South Wind Component", descr = "Instantaneous N–S wind component"),
  list(name = "wind_dir_1d_NS", title = "North-South Wind Component 1d", descr = "Daily N–S wind component"),
  list(name = "CAP9", title = "Circulation Type CAP9", descr = "Circulation type class (9 types)"),
  list(name = "CAP18", title = "Circulation Type CAP18", descr = "Circulation type class (18 types)"),
  list(name = "CAP27", title = "Circulation Type CAP27", descr = "Circulation type class (27 types)"),
  list(name = "GWT8_Z500", title = "GWT8 Z500", descr = "Großwettertyp (8 types) from Z500 field"),
  list(name = "GWT10_SLP", title = "GWT10 SLP", descr = "Großwettertyp (10 types) from SLP field"),
  list(name = "GWT10_Z500", title = "GWT10 Z500", descr = "Großwettertyp (10 types) from Z500 field"),
  list(name = "GWT18_SLP", title = "GWT18 SLP", descr = "Großwettertyp (18 types) from SLP field"),
  list(name = "GWT18_Z500", title = "GWT18 Z500", descr = "Großwettertyp (18 types) from Z500 field"),
  list(name = "GWT26_SLP", title = "GWT26 SLP", descr = "Großwettertyp (26 types) from SLP field"),
  list(name = "GWT26_Z500", title = "GWT26 Z500", descr = "Großwettertyp (26 types) from Z500 field")
)

for(var in variables_fact) {
  var_name <- var$name
  var_title <- var$title
  
  # One-way ANOVA
  formula_str <- paste("UHI ~", var_name)
  anova_result <- aov(as.formula(formula_str), data = meteo_all)
  summary(anova_result)
  eta2 <- etaSquared(anova_result)
  
  # Count and dynamic y position for label
  counts <- meteo_all |>
    group_by(!!sym(var_name)) |>
    summarise(
      n = n(),
      max_y = max(UHI, na.rm = TRUE),
      .groups = "drop"
    ) |>
    mutate(label_y = max_y + 0.15)  # small buffer above max
  
  # Plot
  p <- ggplot(meteo_all, aes(x = !!sym(var_name), y = UHI)) +
    geom_boxplot(fill = "skyblue", alpha = 0.7, outlier.colour = "skyblue") +
    geom_text(
      data = counts,
      aes(x = !!sym(var_name), y = label_y, label = paste0("n = ", n)),
      inherit.aes = FALSE,
      size = 3.5
    ) +
    labs(
      title = paste("UHI distribution by", var_title),
      subtitle = paste("Eta-squared:", round(eta2[1], 2)),
      x = "Weather Type", y = "UHI [K]"
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  print(p)

  ggsave(paste0("../results/Variable Selection/", var_name, "_vs_UHI.png"), plot = p,
         width = 7, height = 5.5, dpi = 300)
    rm(p, eta2, anova_result, counts)
}

```

```{r}
# Categorize precipitation into bins
meteo_all_aggr <- meteo_all_aggr |>
  mutate(precip_cat = cut(
    precip,
    breaks = c(-Inf, 0.3, 5, 10, Inf),
    labels = c("≤ 0.3", "0.3–5", "5–10", "> 10"),
    right = FALSE
  ))

# Get counts and max UHI per group
counts <- meteo_all_aggr |>
  group_by(precip_cat) |>
  summarise(
    n = n(),
    max_y = max(UHI, na.rm = TRUE),
    .groups = "drop"
  ) |>
  mutate(label_y = max_y + 0.15)

# ANOVA
anova_result <- aov(UHI ~ precip_cat, data = meteo_all_aggr)
eta2 <- etaSquared(anova_result)

# Plot
ggplot(meteo_all_aggr, aes(x = precip_cat, y = UHI)) +
  geom_boxplot() +
  geom_text(
    data = counts,
    aes(x = precip_cat, y = label_y, label = paste0("n = ", n)),
    inherit.aes = FALSE,
    size = 3.5
  ) +
  labs(
    title = "UHI distribution by Precipitation Category",
    subtitle = paste("Eta-squared:", round(eta2[1], 2)),
    x = "Precipitation [mm]",
    y = "UHI [K]"
  ) +
  theme_classic()

ggsave("../results/Variable Selection/precip_cat_vs_UHI.png", 
       width = 5, height = 5.5, dpi = 300)
```



# Automated Variable selection

We are going to test different algorithms to select the best variables for our model. 
- Boruta
- Random forest stepwise backwards regression
- Correlation matrix

```{r}
meteo_all <- meteo_all |>
  filter(!is.na(UHI))
model_data <- meteo_all |>
    dplyr::select(
    -time, -Log_NR, -NORD_CHTOPO, -OST_CHTOPO, -LV_03_E, -LV_03_N, -Location,
    -daynight, -air_temp_LCD, -UHI_LCD, -LCZ, -LCZ_mixed, -LU_3, -LU_7
  ) 
predictors <- meteo_all |>
  dplyr::select(
    -time, -Log_NR, -NORD_CHTOPO, -OST_CHTOPO, -LV_03_E, -LV_03_N, -Location,
    -daynight, -air_temp_LCD, -UHI_LCD, -UHI, -LCZ, -LCZ_mixed, -LU_3, -LU_7
  )
  # for variable names that start with "BH_NA", replace NA values with 0
  #mutate(across(starts_with("BH_NA"), ~ replace_na(., 0)))
  
```




```{r}
meteo_daily <- readRDS("../data/final_predictors/Meteo_predictors_daily.rds") |>
  dplyr::filter(daynight == "n") |>
  dplyr::select(-daynight) |>
  mutate(PP_bool = as.factor(PP_bool),
         PP_bool_1d = as.factor(PP_bool_1d),
         PP_bool_3d = as.factor(PP_bool_3d))

all_data_daily <- readRDS("../data/final_predictors/all_data_daily.rds")

UHI_daily <- all_data_daily |>
  dplyr::select(time, UHI, UHI_LCD, daynight) |>
  dplyr::filter(daynight == "n") |>
  dplyr::select(-daynight, -UHI_LCD)

mean_UHI <- UHI_daily |>
  dplyr::group_by(time) |>
  dplyr::summarise(UHI = mean(UHI, na.rm = TRUE), .groups = "drop")

meteo_UHI_daily <- meteo_daily |>
  dplyr::left_join(UHI_daily, by = "time") |>
  dplyr::filter(!is.na(UHI))

meteo_mean_UHI_daily <- meteo_daily |>
  dplyr::left_join(mean_UHI, by = "time") |>
  dplyr::filter(!is.na(UHI))


# get names of numeric variables and factor variables
variables_num <- meteo_daily |>
  dplyr::select(where(is.numeric)) |>
  colnames()

variables_fact <- meteo_daily |>
  dplyr::select(where(is.factor)) |>
  colnames()
```

```{r}
# Filter and compute r for each wind direction
cor_df <- meteo_mean_UHI_daily |>
  #filter(WS < 10) |>
  group_by(WD_NS) |>
  summarise(r2 = (cor(WS, UHI, use = "complete.obs"))^2) |>
  mutate(r_label = paste0("R² (", WD_NS, ") = ", round(r2, 3))) |>
  pull(r_label)

# Combine into one subtitle string
subtitle_text <- paste(cor_df, collapse = "; ")

# Plot with subtitle
meteo_mean_UHI_daily |>
  ggplot(aes(x = WS, y = UHI, color = WD_NS)) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    subtitle = subtitle_text,
    x = "Wind Speed (km/h)",
    y = "UHI [K]",
    color = "Wind Direction"
  ) +
  theme_classic() +
  scale_color_manual(values = c("N" = "darkorange", "S" = "darkcyan")) +
  theme(legend.position = "inside",
        legend.justification = c(1,1),
        legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8))

ggsave("../results/Variable Selection/variables_vs_UHI/WindSpeed_vs_UHI_WD_NS.png", width = 3.5, height = 3.8, dpi = 300)

# same for WD_WE
cor_df <- meteo_mean_UHI_daily |>
  #filter(WS < 10) |>
  group_by(WD_WE) |>
  summarise(r2 = (cor(WS, UHI, use = "complete.obs"))^2) |>
  mutate(r_label = paste0("R² (", WD_WE, ") = ", round(r2, 3))) |>
  pull(r_label)
# Combine into one subtitle string
subtitle_text <- paste(cor_df, collapse = "; ")
# Plot with subtitle
meteo_mean_UHI_daily |>
  ggplot(aes(x = WS, y = UHI, color = WD_WE)) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    subtitle = subtitle_text,
    x = "Wind Speed (km/h)",
    y = "UHI [K]",
    color = "Wind Direction"
  ) +
  theme_classic() +
  scale_color_manual(values = c("W" = "darkorange", "E" = "darkcyan")) +
  theme(legend.position = "inside", 
        legend.justification = c(1,1),
        legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8))
ggsave("../results/Variable Selection/variables_vs_UHI/WindSpeed_vs_UHI_WD_WE.png", width = 3.5, height = 3.8, dpi = 300)


# same for lake wind
cor_df <- meteo_mean_UHI_daily |>
  #filter(WS < 10) |>
  group_by(WD_L_NS) |>
  summarise(r2 = (cor(WS_L, UHI))^2) |>
  mutate(r_label = paste0("R² (", WD_L_NS, ") = ", round(r2, 3))) |>
  pull(r_label)

# Combine into one subtitle string
subtitle_text <- paste(cor_df, collapse = "; ")

# Plot with subtitle
meteo_mean_UHI_daily |>
  ggplot(aes(x = WS_L, y = UHI, color = WD_L_NS)) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    subtitle = subtitle_text,
    x = "Wind Speed (km/h)",
    y = "UHI [K]",
    color = "Wind Direction"
  ) +
  theme_classic() +
  scale_color_manual(values = c("N" = "darkorange", "S" = "darkcyan")) +
  theme(legend.position = "inside",
        legend.justification = c(1,1),
        legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8))

ggsave("../results/Variable Selection/variables_vs_UHI/WindSpeed_lake_vs_UHI_WD_NS.png", width = 3.5, height = 3.8, dpi = 300)

# same for WD_L_WE
cor_df <- meteo_mean_UHI_daily |>
  #filter(WS < 10) |>
  group_by(WD_L_WE) |>
  summarise(r2 = (cor(WS_L, UHI))^2) |>
  mutate(r_label = paste0("R² (", WD_L_WE, ") = ", round(r2, 3))) |>
  pull(r_label)
# Combine into one subtitle string
subtitle_text <- paste(cor_df, collapse = "; ")
# Plot with subtitle
meteo_mean_UHI_daily |>
  ggplot(aes(x = WS_L, y = UHI, color = WD_L_WE)) +
  geom_point(alpha = 0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    subtitle = subtitle_text,
    x = "Wind Speed (km/h)",
    y = "UHI [K]",
    color = "Wind Direction"
  ) +
  theme_classic() +
  scale_color_manual(values = c("W" = "darkorange", "E" = "darkcyan")) +
  theme(legend.position = "inside", 
        legend.justification = c(1,1),
        legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8))
ggsave("../results/Variable Selection/variables_vs_UHI/WindSpeed_lake_vs_UHI_WD_WE.png", width = 3.5, height = 3.8, dpi = 300)

# Plot with subtitle
meteo_mean_UHI_daily |>
  ggplot(aes(x = WS_L, y = UHI, color = WD_L_8)) +
  geom_point(alpha = 0.8) +
  #geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Wind Speed (km/h)",
    y = "UHI [K]",
    color = "Wind Direction"
  ) +
  theme_classic() +
  theme(legend.position = "right", 
        #legend.justification = c(1,1),
        #legend.background = element_rect(fill = "white", color = "black"),
        legend.text = element_text(size = 8),
        plot.subtitle = element_text(size = 8))

ggsave("../results/Variable Selection/variables_vs_UHI/WindSpeed_lake_vs_UHI_WD_8.png", width = 3.5, height = 3.8, dpi = 300)
```

```{r}
# Data frame for storing the results
anova_results <- data.frame(
  Variable = character(),
  Eta_Squared = numeric(),
  p_value = numeric(),
  stringsAsFactors = FALSE
)
for (var in variables_fact) {
  
  # One-way ANOVA
  formula_str <- paste("UHI ~", var)
  anova_result <- aov(as.formula(formula_str), data = meteo_UHI_daily)
  summary(anova_result)
  eta2 <- lsr::etaSquared(anova_result)

  # Store results in the data frame
  anova_results <- rbind(anova_results, data.frame(
    Variable = var,
    Eta_Squared = eta2[1],
    p_value = summary(anova_result)[[1]][["Pr(>F)"]][1]
  ))
}
anova_results <- anova_results |>
  dplyr::arrange(dplyr::desc(Eta_Squared))
print(anova_results)

# same for numerical variables
lm_results <- data.frame(
  Variable = character(),
  R = numeric(),
  R_Squared = numeric(),
  p_value = numeric(),
  stringsAsFactors = FALSE
)
for (var in variables_num) {
  
  # Linear model
  formula_str <- paste("UHI ~", var)
  lm_result <- lm(as.formula(formula_str), data = meteo_UHI_daily)
  summary_lm <- summary(lm_result)
  
  # Store results in the data frame
  lm_results <- rbind(lm_results, data.frame(
    Variable = var,
    R = cor(meteo_UHI_daily[[var]], meteo_UHI_daily$UHI, use = "complete.obs"),
    R_Squared = summary_lm$r.squared,
    p_value = summary_lm$coefficients[2, 4]
  ))
}
# reodrder lm_results by R
lm_results <- lm_results |>
  dplyr::arrange(dplyr::desc(R_Squared))
print(lm_results)

# save as csv
write.csv(anova_results, "../results/Variable Selection/factor_variables_effect.csv")
write.csv(lm_results, "../results/Variable Selection/num_variables_effect.csv")
```
UHI at water sites
```{r}
water_data_daily <- readRDS("../data/final_predictors/all_data_daily.rds") |>
  select(time, UHI, UHI_LCD, daynight, Log_NR, WT) |>
  filter(daynight == "n") |>
  filter(Log_NR == "Log_418" | Log_NR == "Log_422" | Log_NR == "Log_413")

# plot UHI across time, different color for Log_NR
ggplot(water_data_daily, aes(x = time, y = UHI_LCD, color = Log_NR)) +
  geom_point() +
  geom_smooth(se = FALSE) +  # trend lines without confidence bands
  labs(
    title = "UHI at Water Sites",
    x = "Time",
    y = "UHI [K]",
    color = "Log_NR"
  ) +
  theme_minimal() +
  scale_color_manual(
    values = c(
      "Log_418" = "#2255cc",
      "Log_422" = "#44ccdd",
      "Log_413" = "#7744bb"
    )
  ) +
  # add grid line at for every month
  scale_x_datetime(date_labels = "%b", date_breaks = "1 month")

ggsave("../results/Measurement season 2024/UHI_water_MJJASO.png", width = 6, height = 4, dpi = 300)

#Plot correlation between WT and UHI
ggplot(water_data_daily, aes(x = WT, y = UHI_LCD, color = Log_NR)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +  # trend lines without confidence bands
  labs(
    title = "UHI vs Water Temperature",
    x = "Water Temperature [°C]",
    y = "UHI [K]",
    color = "Log_NR"
  ) +
  theme_minimal() +
  scale_color_manual(
    values = c(
      "Log_418" = "#2255cc",
      "Log_422" = "#44ccdd",
      "Log_413" = "#7744bb"
    )
  )

# Calculate Pearson correlation (using complete cases)
r_val <- cor(water_data_daily$WT, water_data_daily$UHI_LCD, use = "complete.obs")
r_squared <- r_val^2
r_squared_text <- paste0("R² = ", round(r_squared, 2))

# Plot
ggplot(water_data_daily, aes(x = WT, y = UHI_LCD, color = Log_NR)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = r_squared_text,
    x = "Water Temperature [°C]",
    y = "UHI [K]",
    color = "Log_NR"
  ) +
  theme_classic() +
  scale_color_manual(
    values = c(
      "Log_418" = "#2255cc",
      "Log_422" = "#44ccdd",
      "Log_413" = "#7744bb"
    )
  )
ggsave(paste0("../results/Variable Selection/variables_vs_UHI/WT_water_sites_vs_UHI.png"), 
         width = 4.5, height = 3.8, dpi = 300)

# calculate mean UHI_LCD across all Log_NR
mean_UHI_water <- water_data_daily |>
  group_by(time) |>
  summarise(UHI_LCD = mean(UHI_LCD, na.rm = TRUE),
            WT = mean(WT, na.rm = TRUE),
            .groups = "drop")

# Plot correlation
r_val <- cor(mean_UHI_water$WT, mean_UHI_water$UHI_LCD, use = "complete.obs")
r_squared <- r_val^2
r_squared_text <- paste0("R² = ", round(r_squared, 2))
# Plot
ggplot(mean_UHI_water, aes(x = WT, y = UHI_LCD)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    title = r_squared_text,
    x = "Water Temperature [°C] \nat water sites 413, 418, 422",
    y = "UHI [K]"
  ) +
  theme_classic()
ggsave(paste0("../results/Variable Selection/variables_vs_UHI/WT_mean_water_sites_vs_UHI.png"), 
         width = 3.5, height = 3.9, dpi = 300)

```


```{r}
# Data frame for storing the results
anova_results <- data.frame(
  Variable = character(),
  Eta_Squared = numeric(),
  p_value = numeric(),
  stringsAsFactors = FALSE
)
for (var in variables_fact) {
  
  # One-way ANOVA
  formula_str <- paste("UHI ~", var)
  anova_result <- aov(as.formula(formula_str), data = meteo_mean_UHI_daily)
  summary(anova_result)
  eta2 <- lsr::etaSquared(anova_result)

  # Store results in the data frame
  anova_results <- rbind(anova_results, data.frame(
    Variable = var,
    Eta_Squared = eta2[1],
    p_value = summary(anova_result)[[1]][["Pr(>F)"]][1]
  ))
}
anova_results <- anova_results |>
  dplyr::arrange(dplyr::desc(Eta_Squared))
print(anova_results)

# same for numerical variables
lm_results <- data.frame(
  Variable = character(),
  R = numeric(),
  R_Squared = numeric(),
  p_value = numeric(),
  stringsAsFactors = FALSE
)
for (var in variables_num) {
  
  # Linear model
  formula_str <- paste("UHI ~", var)
  lm_result <- lm(as.formula(formula_str), data = meteo_mean_UHI_daily)
  summary_lm <- summary(lm_result)
  
  # Store results in the data frame
  lm_results <- rbind(lm_results, data.frame(
    Variable = var,
    R = cor(meteo_mean_UHI_daily[[var]], meteo_mean_UHI_daily$UHI, use = "complete.obs"),
    R_Squared = summary_lm$r.squared,
    p_value = summary_lm$coefficients[2, 4]
  ))
}
# reodrder lm_results by R
lm_results <- lm_results |>
  dplyr::arrange(dplyr::desc(R_Squared))
print(lm_results)

# save as csv
write.csv(anova_results, "../results/Variable Selection/factor_variables_effect_meanUHI.csv")
write.csv(lm_results, "../results/Variable Selection/num_variables_effect_meanUHI.csv")
```


```{r}
for (var in variables_num) {

  # Calculate Pearson correlation coefficient
  r_val <- cor(meteo_mean_UHI_daily[[var]], meteo_mean_UHI_daily$UHI, use = "complete.obs")
  r_squared <- r_val^2
  r_text <- paste0("r = ", round(r_val, 2))
  r_squared_text <- paste0("R² = ", round(r_squared, 2))

  p <- ggplot(meteo_mean_UHI_daily, aes(x = !!sym(var), y = UHI)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +
    labs(
      title = r_squared_text,
      x = var,
      y = "UHI [K]"
    ) +
    theme_classic() +
    theme(legend.position = "none")
  
  print(p)
  ggsave(paste0("../results/Variable Selection/variables_vs_UHI/", var, "_vs_UHI.png"), plot = p, 
         width = 3.5, height = 3.8, dpi = 300)
}
```

```{r}
for (var in variables_fact) {
  
  # One-way ANOVA
  formula_str <- paste("UHI ~", var)
  anova_result <- aov(as.formula(formula_str), data = meteo_mean_UHI_daily)
  summary(anova_result)
  eta2 <- lsr::etaSquared(anova_result)
  
  # Count and dynamic y position for label
  counts <- meteo_mean_UHI_daily |>
    group_by(!!sym(var)) |>
    summarise(
      n = n(),
      max_y = max(UHI, na.rm = TRUE),
      .groups = "drop"
    ) |>
    mutate(label_y = max_y + 0.15)  # small buffer above max
  
  # Plot
  p <- ggplot(meteo_mean_UHI_daily, aes(x = !!sym(var), y = UHI)) +
    geom_boxplot(outlier.colour = "black") +
    geom_text(
      data = counts,
      aes(x = !!sym(var), y = label_y, label = paste0("n = ", n)),
      inherit.aes = FALSE,
      size = 3.5
    ) +
    labs(
      subtitle = paste("Eta²:", round(eta2[1], 2)),
      x = var, y = "UHI [K]"
    ) +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))
  
  print(p)
  
  # get number of levels in the factor variable
  num_levels <- length(unique(meteo_mean_UHI_daily[[var]]))
  width <- ifelse(num_levels > 10, 7, 3.5) # adjust width based on number of levels
  if(num_levels == 8) width <- 5 # for 8-level wind direction

  ggsave(paste0("../results/Variable Selection/variables_vs_UHI/", var, "_vs_UHI.png"), plot = p,
         width = width, height = 3.8, dpi = 300)
}
```

